
####################################################################################
# 20210706 - v1.5 - Pablo Rico
# Deployment Apache Guacamole+Traefik (Docker-Compose)
####################################################################################

####################################################################################
# TOTP RESET
####################################################################################
# Run "docker ps" to get the PostgreSQL container ID and then:
# docker exec -it <container id> psql -U guacamole_user guacamole_db
# To obtain the user_id run:
# SELECT user_id FROM guacamole_user INNER JOIN guacamole_entity ON guacamole_entity.entity_id = guacamole_user.entity_id WHERE guacamole_entity.name = 'USERNAME';
# Update the user_id to reset the TOTP
# UPDATE guacamole_user_attribute SET attribute_value='false' WHERE attribute_name = 'guac-totp-key-confirmed' and user_id = '1';
# quit
####################################################################################

version: '3.3'

# networks
networks:
  guacnetwork:
    driver: bridge


# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.3.0
    restart: always
    volumes:
    - /etc/guacamole/guac-PR/drive:/drive:rw
    - /etc/guacamole/guac-PR/record:/record:rw
    - /etc/guacamole/guac-PR/share:/share:rw
    networks:
      - guacnetwork
  
  
  # postgres
  postgres:
    image: postgres:13
    container_name: postgres_DB
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: U5er.D8-pa5sW0rd
      POSTGRES_USER: guacamole_user
    networks:
      - guacnetwork
    restart: always
    volumes:
      - /etc/guacamole/guac-PR/init:/docker-entrypoint-initdb.d:ro
      - /etc/guacamole/guac-PR/data:/var/lib/postgresql/data:rw
  
  # guacamole
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.3.0
    depends_on:
      - guacd
      - postgres
    environment:
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: U5er.D8-pa5sW0rd
      POSTGRES_USER: guacamole_user
      POSTGRES_USER_REQUIRED: 'true'
      #### UNCOMMENT TO ENABLE LDAP AUTH  ####    
      #LDAP_HOSTNAME: localdomain
      #LDAP_PORT: 389
      #LDAP_ENCRYPTION_METHOD: none
      #LDAP_USER_BASE_DN: OU=Users,DC=localdomain
      #LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      #LDAP_SEARCH_BIND_DN: CN=guacuser,OU=Users,DC=localdomain
      #LDAP_SEARCH_BIND_PASSWORD: gu4c9ASs
      #LDAP_USER_SEARCH_FILTER: (|(memberOf=CN=Guacamole Admins,DC=localdomain)(memberOf=CN=Guacamole Users,DC=localdomain))
      #####  #####  ####  

    links:
      - guacd
    networks:
      - guacnetwork
    ports:
      - 8080/tcp
    restart: always 
    volumes:
      - /etc/guacamole/guac-PR/guac_home:/config:rw
      - /etc/guacamole/guac-PR/tomcatConfig/server.xml:/usr/local/tomcat/conf/server.xml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      #Enable Sticky Sessions (to allow load balancing in case of using more than one traefik instance)
      - "traefik.http.services.guacamole.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.guacamole.loadbalancer.sticky.cookie.name=StickyGuac"
      - "traefik.http.routers.guacamole-http.rule=Host(`guacamole.local`)||PathPrefix(`/`)"
      - "traefik.http.routers.guacamole-http.entrypoints=http"
      - "traefik.http.routers.guacamole-https.rule=Host(`guacamole.local`)||PathPrefix(`/`)"
      - "traefik.http.routers.guacamole-https.entrypoints=https"
      - "traefik.http.routers.guacamole-https.tls=true"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.http.routers.guacamole-http.middlewares=redirect"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      # the middleware 'add-context' must be defined so that the regex rules can be attached to it
      - "traefik.http.routers.guacamole-https.middlewares=add-context"
      # Redirect to /guacamole:
      - "traefik.http.middlewares.add-context.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.add-context.redirectregex.replacement=https://$$1/guacamole"

  loadbalancer:
    image: traefik:2.4
    container_name: traefik
    depends_on:
      - guacamole
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker=true
      #- --providers.docker.watch=true
      - --providers.docker.network=guacamole_guacnetwork
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on address 80
      - --entrypoints.http.address=:80
      - --entryPoints.http.forwardedHeaders.insecure
      # Create an entrypoint "https" listening on address 443
      - --entrypoints.https.address=:443
      - --entryPoints.https.forwardedHeaders.insecure
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # --log.level=DEBUG
      # Enable the Dashboard and API
      - --api.insecure=true
      # TLS configuration
      - --providers.file.filename=/etc/traefik/dynamic_conf/conf.yml
    networks:
      - guacnetwork
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
     #Certificates path
      - /etc/guacamole/guac-PR/ssl/:/config/ssl/:ro
     #Config path
      - /etc/guacamole/guac-PR/traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    restart: always 
    labels:
        - traefik.enable=true
        - traefik.docker.network=guacamole_guacnetwork
